name: bitcoin_tracker
description: Bitcoin Tracker application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.0+2
  rflutter_alert: ^1.1.0
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
